[workspace]
members = ["crates/*"]
resolver = "2"
default-members = ["crates/ped"]

[workspace.package]
edition = "2024"
version = "0.1.0"
publish = false

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = "symbols"

# Kindle/ARMv7 forks used in place of crates.io / stock Servo deps.
[patch.crates-io]
freetype-sys = { git = "https://github.com/einkdisplay/freetype-sys", branch = "master" }
mozjs_sys = { git = "https://github.com/einkdisplay/mozjs", branch = "kindle-armv7-musl" }
