FROM ghcr.io/rust-cross/rust-musl-cross:armv7-musleabihf

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3 cmake ninja-build pkg-config ccache \
        gcc-arm-linux-gnueabihf libc6-dev-armhf-cross \
    && mkdir -p /opt/ccache/bin \
    && ln -s /usr/bin/ccache /opt/ccache/bin/armv7-unknown-linux-musleabihf-gcc \
    && ln -s /usr/bin/ccache /opt/ccache/bin/armv7-unknown-linux-musleabihf-g++ \
    && rm -rf /var/lib/apt/lists/*
